In [1]:
import numpy as np


In [37]:
W = np.ones((4,4))


B = np.array([ 0,
              -1,
              -2,
              -3])

W2 = np.array([1,
               -2,
               4,
               -8])


In [38]:
def sig(v):
    return 1/(1+np.exp(-v))


In [40]:
trails = 50
for i in xrange(trails):
    X = 1*(np.random.uniform(size=(4)) > 0.5)
    parity = np.sum(X) % 2
    nout = 1*(sig(np.dot(W2,np.maximum(np.dot(W,X) + B,0))) > 0.5)
    print (X,parity,nout)
    if parity != nout:
        print "No Match"
        break

(array([0, 1, 1, 1]), 1, 1)
(array([0, 0, 1, 1]), 0, 0)
(array([0, 0, 0, 1]), 1, 1)
(array([1, 1, 0, 1]), 1, 1)
(array([1, 0, 0, 1]), 0, 0)
(array([0, 0, 0, 1]), 1, 1)
(array([0, 1, 1, 0]), 0, 0)
(array([1, 0, 1, 0]), 0, 0)
(array([1, 0, 1, 1]), 1, 1)
(array([1, 0, 0, 1]), 0, 0)
(array([1, 0, 1, 0]), 0, 0)
(array([0, 1, 1, 1]), 1, 1)
(array([0, 1, 1, 0]), 0, 0)
(array([1, 0, 0, 1]), 0, 0)
(array([0, 0, 0, 0]), 0, 0)
(array([1, 1, 1, 1]), 0, 0)
(array([1, 0, 1, 0]), 0, 0)
(array([1, 0, 1, 1]), 1, 1)
(array([1, 1, 0, 0]), 0, 0)
(array([1, 0, 0, 0]), 1, 1)
(array([1, 1, 0, 0]), 0, 0)
(array([1, 0, 0, 1]), 0, 0)
(array([0, 0, 1, 0]), 1, 1)
(array([0, 0, 0, 0]), 0, 0)
(array([1, 1, 0, 0]), 0, 0)
(array([1, 0, 1, 0]), 0, 0)
(array([0, 0, 0, 0]), 0, 0)
(array([1, 0, 1, 1]), 1, 1)
(array([0, 0, 0, 0]), 0, 0)
(array([0, 1, 0, 0]), 1, 1)
(array([0, 0, 0, 1]), 1, 1)
(array([0, 1, 0, 0]), 1, 1)
(array([1, 1, 0, 0]), 0, 0)
(array([1, 1, 1, 0]), 1, 1)
(array([1, 0, 0, 0]), 1, 1)
(array([1, 0, 0, 0])